services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/mattermost.yaml:/etc/grafana/provisioning/dashboards/mattermost.yaml
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_PASS}
    networks:
      - monitoring_net

  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - "9121:9121"
    networks:
      - monitoring_net

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: postgres://${PG_USER}:${PG_PASS}@postgres:5432/${PG_DB}?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - monitoring_net

volumes:
  grafana-storage:

networks:
  monitoring_net:
    external: true
